name: Publish Docs
on:
  push:
    branches:
      - master
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    name: Docs builder and publisher
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install sphinx sphinx-rtd-theme
      - name: Install Gdstk
        run: python setup.py install --user
      - name: Make figures
        shell: bash
        run: for I in docs/*_images.py; python "$I"; done
      - name: Build docs
        run: python setup.py build_sphinx
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          publish_branch: gh-pages
          keep_files: false
          force_orphan: true

