name: Build & publish PyPI packages

on:
  push:
  workflow_dispatch:

jobs:
  make_wheels:
    name: Make MacOs and Widows wheels
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 12
      matrix:
        python-version: ["3.10"]
        os: [macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Optional, use if you use setuptools_scm
        submodules: true  # Optional, use if you have submodules
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        mamba-version: "*"
        channels: conda-forge,defaults
        channel-priority: true
        activate-environment: anaconda-client-env
    - name: Build SDist
      run: |
          mamba install zlib cmake numpy -y
          pipx install numpy
          pipx run build
    - uses: actions/upload-artifact@v3
      with:
          path: dist/*

  make_linux_wheels:
    name: Make Linux wheels
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 12
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Optional, use if you use setuptools_scm
        submodules: true  # Optional, use if you have submodules
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        mamba-version: "*"
        channels: conda-forge,defaults
        channel-priority: true
        activate-environment: anaconda-client-env
    - name: Build SDist
      run: |
          mamba install zlib cmake numpy -y
          python -m pip install numpy
          python setup.py bdist_wheel --universal
    - uses: actions/upload-artifact@v3
      with:
          path: dist/*

  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Optional, use if you use setuptools_scm
        submodules: true  # Optional, use if you have submodules

    - name: Build SDist
      run: pipx run build --sdist

    - uses: actions/upload-artifact@v3
      with:
        path: dist/*.tar.gz


  upload_to_test_pypy:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: [make_sdist, make_wheels, make_linux_wheels]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: artifact
        path: dist

    - uses: pypa/gh-action-pypi-publish@v1.5.1
      continue-on-error: true   # might fail if we don't bump the version
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

  upload_to_pypi:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: [make_sdist, make_wheels, make_linux_wheels]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: artifact
        path: dist

    - uses: pypa/gh-action-pypi-publish@v1.5.1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
