name: Build & publish PyPI packages

on:
  push:
    tags:
      - v[0-9]+.**
  workflow_dispatch:

jobs:
  make_sdist:
    name: Make SDist
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 12
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Optional, use if you use setuptools_scm
        submodules: true  # Optional, use if you have submodules
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        mamba-version: "*"
        channels: conda-forge,defaults
        channel-priority: true
        activate-environment: anaconda-client-env
    - name: Build SDist
      run: |
          mamba install zlib cmake numpy
          python setup.py bdist_wheel
      env:
        CMAKE_GENERATOR: "Ninja"
        CMAKE_TOOLCHAIN_FILE: "conan_paths.cmake"
    - uses: actions/upload-artifact@v3
      with:
          name: packages
          path: "dist/*.whl"


  upload_to_test_pypy:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: [make_sdist]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: artifact
        path: dist

    - uses: pypa/gh-action-pypi-publish@v1.5.1
      continue-on-error: true   # might fail if we don't bump the version
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/

  upload_to_pypi:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: [make_sdist]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: artifact
        path: dist

    - uses: pypa/gh-action-pypi-publish@v1.5.1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
