name: Create release

on:
  push:
    branches: [master]
    tags:
      - 'v*.*'

jobs:
  release_add:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: softprops/action-gh-release@v1
