name: Release Draft
on:
  push:
    tags:
      - "v*"
jobs:
  windows-binaries:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]
    name: Windows build for ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Miniconda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
      - name: Install dependencies
        run: conda install cmake openblas lapack numpy pytest
      - name: Build
        run: python setup.py bdist_wheel
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: dist-${{ matrix.python-version }}
          path: dist/*.whl
  release-draft:
    needs: windows-binaries
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    name: Create draft release
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v2
      - name: Release
        uses: anton-yurchenko/git-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: "true"
          CHANGELOG_FILE: "CHANGELOG.md"
          ALLOW_EMPTY_CHANGELOG: "true"
          ALLOW_TAG_PREFIX: "true"
          RELEASE_NAME_PREFIX: "Release "
        with:
          args: dist-*/*.whl
