name: Create release

on:
  push:
    tags:
      - 'v*.*'

jobs:
  release_add:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: softprops/action-gh-release@v1
